config/routes.rb
require 'resque_web'

resque_web_constraint = lambda do |request|
  current_user = request.env['warden'].user
  current_user.present? && current_user.admin?
end
Rails.application.routes.draw do
  use_doorkeeper
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
      resources :sprints, only: [:index, :create]
      resources :backlogs, only: [:index]
      resources :pay_items, only: [:index]
      resources :tasks, except: [:new, :edit, :destroy] do
        member do
          get  'work_periods' => :work_periods, :as => 'work_periods'
          post 'work_periods' => :log_hours, :as => 'log_hours'
          get :children
        end
      end
      get "tasks/:id/comments" => "tasks#comments"
      post "tasks/:id/comments" => "tasks#post_comment"
    end
  end

  resources :cost_types
  resources :costs
  resources :wages
  resources :users, only: [] do
    collection do
      get :search_users
    end
  end
  resources :work_periods do
    collection do
      get :filter_by
      get :check_budget
      post :send_exceeded_log_hours_notification
    end
  end
  resources :high_schools, only: [:index]
  resources :removed_tasks, only: [:index]
  resources :addresses do
    collection do
      get :find_place
    end
  end
  resources :tasks do
    member do
      get :show_task
    end
    collection do
      get :task_vital_tasks
      get :task_pay_item
      get :filter_tasks
      get :search_tasks
      get :check_task_budget
    end

    member do
      get :remaining_budget
      get :task_summary
      get :task_snapshot
      put :check_task_date_range
      match :check_budget, via: [:get, :put]
      put :remove_task
      put :recover_task
    end
  end
  resources :task_users do
    collection do
      put :switch_role
    end
  end

  resources :pay_item_categories, only: [] do
    collection do
      get :search_pay_items
    end
  end

  namespace :reports do
    resource :staff_hours, only: [:show]
    resource :budget_reports, only: [:show]
  end

  get 'home/index'
  get 'home/user_list'
  get 'home/pay_items'

  # reporting
  get 'reports' => :index, controller: :reports
  get 'reports/staff_hours_view' => :index, controller: :reports
  get 'reports/budget_reports_view' => :index, controller: :reports

  # timesheet
  get 'timesheet/current_timesheet', as: :current_timesheet
  post 'timesheet/send_timesheet', as: :send_timesheet

  #xero authentication
  get 'xero_session/new' => 'xero_session#new', as: :xero_new_session

  devise_for :users,
             controllers: {
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords'
             }
  root 'home#index'
  get 'task/:id' => 'tasks#main', as: :task_id
end

app/models/wage.rb
class Wage < ActiveRecord::Base
  has_many :users
end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  before_action :set_wage, only: [:show, :edit, :update, :destroy]

  # GET /wages
  # GET /wages.json
  def index
    @wages = Wage.all
  end

  # GET /wages/1
  # GET /wages/1.json
  def show
  end

  # GET /wages/new
  def new
    @wage = Wage.new
  end

  # GET /wages/1/edit
  def edit
  end

  # POST /wages
  # POST /wages.json
  def create
    @wage = Wage.new(wage_params)

    respond_to do |format|
      if @wage.save
        format.html { redirect_to @wage, notice: 'Wage was successfully created.' }
        format.json { render :show, status: :created, location: @wage }
      else
        format.html { render :new }
        format.json { render json: @wage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wages/1
  # PATCH/PUT /wages/1.json
  def update
    respond_to do |format|
      if @wage.update(wage_params)
        format.html { redirect_to @wage, notice: 'Wage was successfully updated.' }
        format.json { render :show, status: :ok, location: @wage }
      else
        format.html { render :edit }
        format.json { render json: @wage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wages/1
  # DELETE /wages/1.json
  def destroy
    @wage.destroy
    respond_to do |format|
      format.html { redirect_to wages_url, notice: 'Wage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wage
      @wage = Wage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wage_params
      params.require(:wage).permit(:is_salary, :rate, :description)
    end
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/wages/_form.html.erb
<%= simple_form_for(@wage, :html =>{ class: 'ui form'}) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input :is_salary %>
  </div>
  <div class="field">
    <%= f.input :rate %>
  </div>
  <div class="field">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wages/edit.html.erb
<h1>Editing Wage</h1>

<%= render 'form' %>

<%= link_to 'Show', @wage %> |
<%= link_to 'Back', wages_path %>

app/views/wages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wages</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Is salary</th>
      <th>Rate</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wages.each do |wage| %>
      <tr>
        <td><%= wage.is_salary %></td>
        <td><%= wage.rate %></td>
        <td><%= wage.description %></td>
        <td><%= link_to 'Show', wage %></td>
        <td><%= link_to 'Edit', edit_wage_path(wage) %></td>
        <td><%= link_to 'Destroy', wage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wage', new_wage_path %>

app/views/wages/new.html.erb
<h1>New Wage</h1>

<%= render 'form' %>

<%= link_to 'Back', wages_path %>

app/views/wages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is salary:</strong>
  <%= @wage.is_salary %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @wage.rate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wage.description %>
</p>

<%= link_to 'Edit', edit_wage_path(@wage) %> |
<%= link_to 'Back', wages_path %>