config/routes.rb
require 'resque_web'

resque_web_constraint = lambda do |request|
  current_user = request.env['warden'].user
  current_user.present? && current_user.admin?
end
Rails.application.routes.draw do
  use_doorkeeper
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
      resources :sprints, only: [:index, :create]
      resources :backlogs, only: [:index]
      resources :pay_items, only: [:index]
      resources :tasks, except: [:new, :edit, :destroy] do
        member do
          get  'work_periods' => :work_periods, :as => 'work_periods'
          post 'work_periods' => :log_hours, :as => 'log_hours'
          get :children
        end
      end
      get "tasks/:id/comments" => "tasks#comments"
      post "tasks/:id/comments" => "tasks#post_comment"
    end
  end

  resources :cost_types
  resources :costs
  resources :wages
  resources :users, only: [] do
    collection do
      get :search_users
    end
  end
  resources :work_periods do
    collection do
      get :filter_by
      get :check_budget
      post :send_exceeded_log_hours_notification
    end
  end
  resources :high_schools, only: [:index]
  resources :removed_tasks, only: [:index]
  resources :addresses do
    collection do
      get :find_place
    end
  end
  resources :tasks do
    member do
      get :show_task
    end
    collection do
      get :task_vital_tasks
      get :task_pay_item
      get :filter_tasks
      get :search_tasks
      get :check_task_budget
    end

    member do
      get :remaining_budget
      get :task_summary
      get :task_snapshot
      put :check_task_date_range
      match :check_budget, via: [:get, :put]
      put :remove_task
      put :recover_task
    end
  end
  resources :task_users do
    collection do
      put :switch_role
    end
  end

  resources :pay_item_categories, only: [] do
    collection do
      get :search_pay_items
    end
  end

  namespace :reports do
    resource :staff_hours, only: [:show]
    resource :budget_reports, only: [:show]
  end

  get 'home/index'
  get 'home/user_list'
  get 'home/pay_items'

  # reporting
  get 'reports' => :index, controller: :reports
  get 'reports/staff_hours_view' => :index, controller: :reports
  get 'reports/budget_reports_view' => :index, controller: :reports

  # timesheet
  get 'timesheet/current_timesheet', as: :current_timesheet
  post 'timesheet/send_timesheet', as: :send_timesheet

  #xero authentication
  get 'xero_session/new' => 'xero_session#new', as: :xero_new_session

  devise_for :users,
             controllers: {
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords'
             }
  root 'home#index'
  get 'task/:id' => 'tasks#main', as: :task_id
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    # TASKS CONTROLLER
    class TasksController < ApiController
      before_action :set_task, except: [:index, :create]
      before_action :ensure_task_present, except: [:index, :create]

      def index
        @tasks = TaskService.search(task_search_params)
        render 'index.json.jbuilder', status: :ok
      end

      def create
        @task, error = TaskService.create(user_id: current_user.id,
                                          options: create_task_params)
        if error
          render json: error, status: :unprocessable_entity
        else
          render 'task.json.jbuilder', status: :ok
        end
      end

      def show
        render 'show.json.jbuilder', status: :ok
      end

      def update
        if @task.update(update_params)
          render 'task_summary.json.jbuilder', status: :ok
        else
          render json: { error: true, error_code: 'TASK-001',
                         message:  @task.errors.full_messages.join(', ') }
        end
      end

      def destroy
        @task.destroy
        head :no_content
      end

      def comments
        @comments = @task.comments
        render 'comments.json.jbuilder', status: :ok
      end

      def post_comment
        @comment = @task.comments.build(user_id: current_user.id,
                                        comment: params[:body])
        if @comment.save
          render 'comment.json.jbuilder', status: :ok
        else
          render json: { error: true, error_code: 'COMMENT-001',
                         message:  @comment.errors.full_messages.join(', ') }
        end
      end

      def work_periods
        @work_periods = @task.filter_work_periods(work_periods_filter_params)
        # NO RESPONSE BOBY PROVIDED IN APIARRY DOC
        head :no_content, status: :ok
      end

      def log_hours
        @work_period, error = WorkPeriodService.create(task_id: @task.id,
                                                       user_id: current_user.id,
                                                       params: log_hours_params)
        if error
          render json: error, status: :unprocessable_entity
        else
          # render 'work_period.json.jbuilder'
          # NO RESPONSE BOBY PROVIDED IN APIARRY DOC
          head :no_content, status: :ok
        end
      end

      def children
        @tasks = @task.children
        render 'index.json.jbuilder', status: :ok
      end

      private

      def set_task
        @task = Task.find_by(id: params[:id])
      end

      def update_params
        params.permit(:title, :description, :pay_rate)
      end

      def ensure_task_present
        render json: { error: true, error_code: 'TASK-404',
                       message: 'Task not Found' } unless @task && return
      end

      def work_periods_filter_params
        params.permit(:start_time, :amount_hours, :description)
      end

      def log_hours_params
        params.permit(:start_time, :amount_hours, :description,
                      :end_time, :date_worked, :progress, :start_date,
                      :end_date)
      end

      def task_search_params
        params.permit(:status, :assignee, :project, :priority)
      end

      def create_task_params
        # AS GIVEN IS APIARRAY DOC
        # params.permit(:status, :assignee, :project, :priority)
        # TODO
        params.permit(:title, :description, :target_start, :actual_start,
                      :target_finish, :actual_finish, :actual_finish,
                      :budgeted_cost, :actual_cost, :priority, :parent_id,
                      :pay_rate, :escalation_manager,
                      pay_item_attributes: [:earnings_rate_id, :name],
                      user_ids: [])
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy,
                                  :task_summary, :task_snapshot,
                                  :check_task_date_range,
                                  :check_budget, :check_task_budget,
                                  :remove_task, :recover_task,
                                  :remaining_budget, :show_task]

  def main
    @task = Task.find_by_id(params[:id])
    @today = Time.now.strftime('%Y-%m-%d')
    @work_period = WorkPeriod.new
  end

  def task_vital_tasks
    if params[:id]
      selected_task = Task.find(params[:id])
      @tasks = selected_task.self_and_descendants.created
    else
      @tasks = Task.created.where(depth: 0)
    end
    @tasks = @tasks.paginate(page: params[:page] || 1, per_page: params[:per_page] || 20)
    @total_count = @tasks.count
  end

  def task_pay_item
    if params[:name]
      @tasks = Task.includes(:pay_item).where(pay_items: {name: params[:name]})
    end
    @tasks = @tasks.paginate(page: params[:page] || 1, per_page: params[:per_page] || 20)
    @total_count = @tasks.count
  end

  def filter_tasks
    if params[:task]
      @tasks = Task.created.includes(:task_users).where(vital_task_params)
    else
      @tasks = Task.created
    end
    @tasks = @tasks.paginate(page: params[:page] || 1, per_page: params[:per_page] || 20)
    @total_count = @tasks.count
  end

  def remaining_budget
    if @task.work_periods.count.nonzero?
      render json: { error: 'This parent task contains logged hours.
        Please remove them before continuing.' },
             status: :unprocessable_entity
    end
  end

  def search_tasks
    @tasks = if params[:term]
      task_code_match = Task.find_by_task_code(params[:term])
      if task_code_match
        Task.where(id: task_code_match.id)
      else
        Task.search_by_title(params[:term])
      end
    else
      Task.all
    end
  end
  def task_summary
  end

  def task_snapshot
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.get_tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @user_ids = task_params[:user_ids].reject do |i|
      i.empty? || i.to_i == current_user.id ||
        i.to_i == task_params[:escalation_manager]
    end
    updated_params = task_params.merge(user_ids: @user_ids)
    updated_params.delete(:escalation_manager)
    @task = Task.new(updated_params)
    @task.actual_cost = calc_actual(@task)
    if params[:increase_parents_budget] == 'true'
      @p_task = Task.find(params[:task][:parent_id])
      new_budget = @p_task.budgeted_cost + @task.budgeted_cost.to_f
      @p_task.update(budgeted_cost: new_budget)
      @p_task.notify_increase_in_budget(current_user, @task.budgeted_cost.to_f, params[:task][:title], true)
    end

    e_manager = task_params[:escalation_manager].present? ? task_params[:escalation_manager] : find_escalation_manager

    respond_to do |format|
      if @task.save
        @task.task_users.create(user_id: e_manager,
                                task_role: TaskUser::TASK_ROLES[
                                  :escalation_manager])
        @task.task_users.create(user: current_user, isOwner: true,
                                task_role: TaskUser::TASK_ROLES[
                                  :task_owner])
        format.html do
          redirect_to "#{root_url}#task_id=#{@task.id}",
                      notice: 'Task was successfully created.'
        end
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # @param [Task] task
  def calc_actual(task)
    0 if task.children.count.zero?
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if params[:task][:parent_id].present? &&
       params[:task][:parent_id] != @task.parent_id
      assign_new_parent
    else
      update_task_info
    end
  end

  def find_escalation_manager
    escalation_manager = User.find_by(email: "michael.qiu@gradready.com.au")
    if escalation_manager.present?
      escalation_manager.id
    else
      e_manager = User.where(role: 'manager').first
      e_manager.id
    end
  end

  def check_task_date_range
    if @task.out_of_parent_date?(task_params[:target_start],
                                 task_params[:target_finish])
      render json: {}, status: 406
    else
      update_task_info
    end
  end

  def check_budget
    if request.method == 'PUT'
      update_task_info
    else
      if @task.out_of_parent_budget? task_params[:budgeted_cost]
        render json: { message: "Task budget is out of parent's budget" },
               status: 406
      else
        render json: { message: "Task budget is within parent's budget" },
               status: 409
      end
    end
  end

  def check_task_budget
    render json: 'Task no found', status: :unprocessable_entity unless @task
    if @task.child_out_of_budget?(params[:budgeted_cost])
      render json: { message: "Budget is out of task's budget" }, status: 406
    else
      render json: { message: "Budget is within task's budget" }, status: 409
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html do
        redirect_to tasks_url,
                    notice: 'Task was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def remove_task
    @task.self_and_descendants.sort_by(&:depth).reverse.each do |task|
      c = task.actual_cost <= 0 ? 1 : task.actual_cost
      task.update(budgeted_cost: c, status: 'removed')
    end

    respond_to do |format|
      format.html do
        redirect_to tasks_url,
                    notice: 'Task was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def recover_task
    @task.recover_task
    respond_to do |format|
      format.html do
        redirect_to removed_tasks_url,
                    notice: 'Task was successfully restored.'
      end
      format.json { head :no_content }
    end
  end

  def show_task
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params[:task][:weekly_reports_start] = params[:task][:weekly_reports_start].to_i if params[:task][:weekly_reports_start].present?
    params.require(:task).permit(:title, :description, :target_start,
                                 :actual_start, :target_finish, :actual_finish,
                                 :budgeted_cost, :actual_cost, :parent_id,
                                 :priority, :pay_rate, :escalation_manager,
                                 :project_code,
                                 :weekly_reports_start,
                                 pay_item_attributes: [:earnings_rate_id,
                                                       :name],
                                 user_ids: [])
  end

  def task_increase_parents_budget_params
    params.require(:task).permit(:increase_parents_budget,
                                 increase_parents_budget_attributes:
                                 [:parent_id, :amount])
  end

  def task_decrease_parents_budget_params
    params.require(:task).permit(:decrease_parents_budget,
                                 decrease_parents_budget_attributes:
                                 [:parent_id, :amount])
  end

  def task_decrease_all_parents_budget_params
    params.require(:task).permit(:decrease_all_parents_budget,
                                 decrease_parents_budget_attributes:
                                 [:parent_id, :amount])
  end

  def vital_task_params
    params.require(:task).permit(:depth, :is_leaf,
                                 task_users: [:user_id, :task_role])
  end

  def update_task_info
    @task.notify_out_of_parent_date if @task.out_of_parent_date?(
      task_params[:target_start], task_params[:target_finish]
    )
    if @task.out_of_parent_budget? task_params[:budgeted_cost]

      @task.notify_out_of_budget(current_user, task_params[:budgeted_cost])
      increase_parents_budget if task_increase_parents_budget_params[
        :increase_parents_budget] == 'true'

    end

    respond_to do |format|
      if @task.update(task_params)
        if task_decrease_all_parents_budget_params[
          :decrease_all_parents_budget] == 'true'
          @task.decrease_ancestors_budget(
            task_decrease_all_parents_budget_params[
            :decrease_parents_budget_attributes][:amount].to_d
          )
        end

        if @task.pay_item.earnings_rate_id.blank? 
          unassigned_item = PayItemCategory.find_by_name('Unassigned Item')
          @task.pay_item.update(name: unassigned_item.name, earnings_rate_id: unassigned_item.earnings_rate_id)
        end
        format.html do
          redirect_to home_index_path,
                      notice: 'Task was successfully updated.'
        end
        format.json { render :task_summary, status: :ok }
      else
        format.html { render :edit }
        format.json do
          render json: @task.errors.full_messages.join('\n'),
                 status: :unprocessable_entity
        end
      end
    end
  end

  def increase_parents_budget
    @c_task = Task.find(params[:id]) if(params[:id].present?)
    @p_task = Task.find(
      task_increase_parents_budget_params[
        :increase_parents_budget_attributes][:parent_id]
    )
    new_budget = @p_task.budgeted_cost +
                 task_increase_parents_budget_params[
                   :increase_parents_budget_attributes][:amount].to_f

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_add_time.html.erb
<div class="ui modal add-time-modal">
  <i class="close icon"></i>
  <div class="header">
    Add work Period
  </div>
  <div id="time_submission_form" class="content">
  <%= simple_form_for(@work_period, :html =>{ class: 'ui equal width form'}) do |f| %>
    <%= f.text_field :task_id, hidden: true, value: task.id %>
    <div class="three fields">
            <div class="field">
                <label>Date</label>
        <%= f.text_field :date_worked, value: @today, class: 'datetimepicker' %>
            </div>
            <div class="field">
                <label>Time Worked (Hours)</label>
        <%= f.text_field :amount_hours, value: 0 %>
            </div>
      <div class="field">
        <label>Task Progress (%)</label>
        <%= f.number_field :progress, value: 0, min: 0, max: 100 %>
      </div>
    </div>
    <div class="field">
      <label>Description</label>
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      Cancel
    </div>
      <%= f.button_tag 'Add', class: "ui green labeled icon button", id: "submit_work_period", type:'button' %>
  </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task, :html =>{ class: 'ui form'}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :target_start %><br>
    <%= f.datetime_select :target_start %>
  </div>
  <div class="field">
    <%= f.label :actual_start %><br>
    <%= f.datetime_select :actual_start %>
  </div>
  <div class="field">
    <%= f.label :target_finish %><br>
    <%= f.datetime_select :target_finish %>
  </div>
  <div class="field">
    <%= f.label :actual_finish %><br>
    <%= f.datetime_select :actual_finish %>
  </div>
  <div class="field">
    <%= f.label :budgeted_cost %><br>
    <%= f.text_field :budgeted_cost %>
  </div>
  <div class="field">
    <%= f.label :actual_cost %><br>
    <%= f.text_field :actual_cost %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
    <div class="field">
      <%= f.label :parent %> <br>
      <%= f.select :parent_id, [nil] + nested_set_options(Task, @task) {|i| "#{'-' * i.level} #{i.title}" }, :html=> {class: 'ui dropdown'} %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_home_form.html.erb
<div class="content">
<%= simple_form_for(@task, :html =>{ class: 'ui equal width form error content create-task-form'}) do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :parent_id, 'Parent' %>
      <div class="ui search fluid add-task-parent-chooser">
        <div class='ui icon input'>
          <%= text_field_tag :task_parent, nil,  class: 'prompt' %>
          <i class="dropdown icon"></i>
        </div>
      </div>
      <%= f.hidden_field :parent_id, value: nil %>
    </div>
    <div class="fields">
      <div class="field">
        <%= f.label :remaining_budget, 'Budget to be Allocated' %>
        <%= f.label :remaining_budget_value, '0', class: 'remaining_budget_value' %>
      </div>
      <div class="field">
        <%= f.label :pay_item %>
        <div class='ui icon input'>
            <%= select_tag :task_pay_item, options_for_select(pay_item_options),  class: 'ui search dropdown' %>
        </div>
        <!-- <div class="ui search pay-item-chooser">
          <div class='ui icon input'>
            <%= text_field_tag :task_pay_item, nil,  class: 'prompt' %>
            <i class="dropdown icon"></i>
          </div>
        </div> -->
        <%= f.simple_fields_for 'pay_item_attributes', @task do |p| %>
          <%= p.hidden_field :earnings_rate_id, value: nil %>
          <%= p.hidden_field :name, value: nil %>
        <% end %>
      </div>
    </div>
    <div class="fields">
      <div class="field">
        <%= f.label :budgeted_cost %>
        <%= f.number_field :budgeted_cost %>
      </div>
    </div>
    <div class="fields">
    <div class="field">
      <%= f.label :target_start %>
      <%= f.text_field :target_start, class: 'datetimepicker' %>
    </div>
    <div class="field">
      <%= f.label :target_finish %>
      <%= f.text_field :target_finish, class: 'datetimepicker' %>
    </div>
    </div>


    <div class="fields">
      <div class="field">
        <%= f.label :escalation_manager %>
        <%= f.select :escalation_manager, options_for_select(user_options, 1), {}, { class: 'ui search dropdown' } %>
      </div>
      <div class="field">
        <%= f.label :users, 'Members' %>
        <%= f.association :users, label: false, collection: user_options, input_html: { class: 'ui fluid search dropdown' }%>
      </div>
    </div>
    <div class="field">
      <%= f.label :colour_tcte, "Colour TC/TE in budget report" %>
      <%= f.check_box :colour_tcte %>
    </div>
<% end %>
</div>
<div class="actions">
  <button id="submit_task_form" class="ui green button">Submit</button>
</div>

app/views/tasks/_tree.html.erb
<%= content_tag :div,class: 'item', href: task_id_path(id: task.id), :id => dom_id(task) do %>
    <a href="<%= task_id_path(id: task.id)%>"><%= task.title %></a>
    <%= content_tag :div, class: "list"  do %>
        <% for child in task.children do %>
            <%= render :partial => "tasks/tree", :locals => {:task => child }%>
        <% end %>
    <% end unless task.leaf? %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>
<div class="ui selection dropdown stats-dropdown">
  <div class="default text">Vital stats</div>
  <input type="hidden" name="selected-vital-stat" class="task-vital-stats">
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item" data-value="due-date">Due Date</div>
    <div class="item" data-value="time-elapsed">% Time Elapsed</div>
    <div class="item" data-value="task-completion">% Task Competed</div>
    <div class="item" data-value="budget-spent">% Budget Spent</div>
    <div class="item" data-value="task-budget-ratio">% Task Completed : % Budget Spent</div>
    <div class="item" data-value="task-self-complete">% Task Competed by Me</div>
    <div class="item" data-value="budget-self-spent">% Budget Spent by Me</div>
  </div>
</div>
<div class="ui selection dropdown order-dropdown">
  <div class="default text">Order</div>
  <input type="hidden" name="selected-vital-order" class="task-order-direction">
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item" data-value="asc">Ascending</div>
    <div class="item" data-value="desc">Descending</div>
  </div>
</div>
<table  class="ui celled table tasks-table">
  <thead>
    <tr>
      <th>Project</th>
      <th class="title">Task</th>
      <th>Description</th>
      <th>Priority</th>
      <th class="due-date">Due Date</th>
      <th class="time-elapsed">% Time Elapsed</th>
      <th class="task-completion">% Task Competed</th>
      <th class="budget-spent">% Budget Spent</th>
      <th class="task-budget-ratio">% Task Completed : % Budget Spent</th>
      <th class="task-self-complete">% Task Competed by Me</th>
      <th class="budget-self-spent">% Budget Spent by Me</th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= render partial: 'tasks/tree', locals: {task: task} %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td data-sort-value=<%= task.target_finish.try(:to_i) %> >
          <%= task.target_finish.try(:strftime, "%d/%m/%Y") %>
        </td>
        <td><%= number_to_percentage(task.time_elapsed, precision:2) %></td>
        <td><%= number_to_percentage(task.task_completed, precision:2) %></td>
        <td><%= number_to_percentage(task.budget_spent_ratio, precision:2) %></td>
        <td><%= task.task_completed_over_budget_consumed.round(2) %></td>
        <td><%= number_to_percentage(task.task_completed_by_user(current_user.id), precision:2) %></td>
        <td><%= number_to_percentage(task.budget_spent_ratio_by_user(current_user.id), precision:2) %></td>
        <!--<td><%= link_to 'Show', task %></td>-->
        <!--<td><%= link_to 'Edit', edit_task_path(task) %></td>-->
        <!--<td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/main.html.erb
<h1><%= @task.title %></h1>
<div class="ui grid container">
  <div class="row">
    <div class="twelve wide column">
      <div class="row">
        <button id="add_time" class="positive ui button" tabindex="0">
          Add Working Hours
        </button>
        <%=link_to "Close", root_path, class: "btn ui button"%>
        <div class="ui basic label">
          Users
          <div class="detail"><%= @task.users.count %></div>
        </div>
      </div>

      <br>
      <h3>Log Hours</h3>
      <div class="row">
        <table class="ui celled table">
          <thead>
            <th>ID</th>
            <th>amount_hours </th>
            <th>date_worked</th>
            <th>start_time</th>
            <th>progress</th>
            <th>pay_rate</th>
          </thead>
          <tbody>
            <% @task.work_periods.each do |wp| %>
              <tr>
                <td><%= wp.id %></td>
                <td><%= wp.amount_hours.to_f.round(2) %></td>
                <td><%= wp.date_worked.strftime("%Y/%m/%d") %></td>
                <td><%= wp.start_time.strftime("%H:%M:%S") rescue nil %></td>
                <td><%= wp.progress %></td>
                <td><%= wp.pay_rate %></td>
              </tr>
            <% end -%>
          </tbody>
        </table>
      </div>
    </div>

    <div class="four wide column">
      <table class="ui celled table">
        <tbody>
        <tr>
          <td>Budgeted Cost</td>
          <td><%= @task.budgeted_cost %></td>
        </tr>
        <tr>
          <td>Actual Cost</td>
          <td><%= @task.actual_cost %></td>
        </tr>
        <tr>
          <td>Sub Tasks</td>
          <td><%= @task.children_count %></td>
        </tr>
        <tr>
          <td>Start</td>
          <td><%= @task.target_start.to_formatted_s(:short) %></td>
        </tr>
        <tr>
          <td>Finish</td>
          <td><%= @task.target_finish.to_formatted_s(:short) %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="sixteen wide column">
    </div>
    <div class="row">
      <div class="two wide column">

      </div>
      <div class="two wide column"></div>
    </div>
  </div>
  <%= render partial: 'tasks/add_time', locals: {task: @task} %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Target Start:</strong>
  <%= @task.target_start %>
</p>

<p>
  <strong>Actual Start:</strong>
  <%= @task.actual_start %>
</p>

<p>
  <strong>Target finish:</strong>
  <%= @task.target_finish %>
</p>

<p>
  <strong>Actual finish:</strong>
  <%= @task.actual_finish %>
</p>

<p>
  <strong>Budgeted cost:</strong>
  <%= @task.budgeted_cost %>
</p>

<p>
  <strong>Actual cost:</strong>
  <%= @task.actual_cost %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Tree</strong>
  <%= render :partial => "tasks/tree", :locals => {:task => @task} %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/show_task.html.erb
<div id="show-task-container">
</div>