config/routes.rb
require 'resque_web'

resque_web_constraint = lambda do |request|
  current_user = request.env['warden'].user
  current_user.present? && current_user.admin?
end
Rails.application.routes.draw do
  use_doorkeeper
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
      resources :sprints, only: [:index, :create]
      resources :backlogs, only: [:index]
      resources :pay_items, only: [:index]
      resources :tasks, except: [:new, :edit, :destroy] do
        member do
          get  'work_periods' => :work_periods, :as => 'work_periods'
          post 'work_periods' => :log_hours, :as => 'log_hours'
          get :children
        end
      end
      get "tasks/:id/comments" => "tasks#comments"
      post "tasks/:id/comments" => "tasks#post_comment"
    end
  end

  resources :cost_types
  resources :costs
  resources :wages
  resources :users, only: [] do
    collection do
      get :search_users
    end
  end
  resources :work_periods do
    collection do
      get :filter_by
      get :check_budget
      post :send_exceeded_log_hours_notification
    end
  end
  resources :high_schools, only: [:index]
  resources :removed_tasks, only: [:index]
  resources :addresses do
    collection do
      get :find_place
    end
  end
  resources :tasks do
    member do
      get :show_task
    end
    collection do
      get :task_vital_tasks
      get :task_pay_item
      get :filter_tasks
      get :search_tasks
      get :check_task_budget
    end

    member do
      get :remaining_budget
      get :task_summary
      get :task_snapshot
      put :check_task_date_range
      match :check_budget, via: [:get, :put]
      put :remove_task
      put :recover_task
    end
  end
  resources :task_users do
    collection do
      put :switch_role
    end
  end

  resources :pay_item_categories, only: [] do
    collection do
      get :search_pay_items
    end
  end

  namespace :reports do
    resource :staff_hours, only: [:show]
    resource :budget_reports, only: [:show]
  end

  get 'home/index'
  get 'home/user_list'
  get 'home/pay_items'

  # reporting
  get 'reports' => :index, controller: :reports
  get 'reports/staff_hours_view' => :index, controller: :reports
  get 'reports/budget_reports_view' => :index, controller: :reports

  # timesheet
  get 'timesheet/current_timesheet', as: :current_timesheet
  post 'timesheet/send_timesheet', as: :send_timesheet

  #xero authentication
  get 'xero_session/new' => 'xero_session#new', as: :xero_new_session

  devise_for :users,
             controllers: {
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords'
             }
  root 'home#index'
  get 'task/:id' => 'tasks#main', as: :task_id
end

app/controllers/cost_types_controller.rb
class CostTypesController < ApplicationController
  before_action :set_cost_type, only: [:show, :edit, :update, :destroy]

  # GET /cost_types
  # GET /cost_types.json
  def index
    @cost_types = CostType.all
  end

  # GET /cost_types/1
  # GET /cost_types/1.json
  def show
  end

  # GET /cost_types/new
  def new
    @cost_type = CostType.new
  end

  # GET /cost_types/1/edit
  def edit
  end

  # POST /cost_types
  # POST /cost_types.json
  def create
    @cost_type = CostType.new(cost_type_params)

    respond_to do |format|
      if @cost_type.save
        format.html { redirect_to @cost_type, notice: 'Cost type was successfully created.' }
        format.json { render :show, status: :created, location: @cost_type }
      else
        format.html { render :new }
        format.json { render json: @cost_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cost_types/1
  # PATCH/PUT /cost_types/1.json
  def update
    respond_to do |format|
      if @cost_type.update(cost_type_params)
        format.html { redirect_to @cost_type, notice: 'Cost type was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost_type }
      else
        format.html { render :edit }
        format.json { render json: @cost_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_types/1
  # DELETE /cost_types/1.json
  def destroy
    @cost_type.destroy
    respond_to do |format|
      format.html { redirect_to cost_types_url, notice: 'Cost type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_type
      @cost_type = CostType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_type_params
      params.require(:cost_type).permit(:cost_type)
    end
end

app/helpers/cost_types_helper.rb
module CostTypesHelper
end

app/views/cost_types/_form.html.erb
<%= form_for(@cost_type, :html =>{ class: 'ui form'}) do |f| %>
  <% if @cost_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost_type.errors.count, "error") %> prohibited this cost_type from being saved:</h2>

      <ul>
        <% @cost_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_type %>
    <%= f.text_field :cost_type %>
  </div>

  <div class="field ui">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cost_types/edit.html.erb
<h1>Editing Cost Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost_type %> |
<%= link_to 'Back', cost_types_path %>

app/views/cost_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cost Types</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cost_types.each do |cost_type| %>
      <tr>
        <td><%= cost_type.cost_type %></td>
        <td><%= link_to 'Show', cost_type %></td>
        <td><%= link_to 'Edit', edit_cost_type_path(cost_type) %></td>
        <td><%= link_to 'Destroy', cost_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost type', new_cost_type_path %>

app/views/cost_types/new.html.erb
<h1>New Cost Type</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_types_path %>

app/views/cost_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cost_type.cost_type %>
</p>

<%= link_to 'Edit', edit_cost_type_path(@cost_type) %> |
<%= link_to 'Back', cost_types_path %>