config/routes.rb
require 'resque_web'

resque_web_constraint = lambda do |request|
  current_user = request.env['warden'].user
  current_user.present? && current_user.admin?
end
Rails.application.routes.draw do
  use_doorkeeper
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque_web'
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
      resources :sprints, only: [:index, :create]
      resources :backlogs, only: [:index]
      resources :pay_items, only: [:index]
      resources :tasks, except: [:new, :edit, :destroy] do
        member do
          get  'work_periods' => :work_periods, :as => 'work_periods'
          post 'work_periods' => :log_hours, :as => 'log_hours'
          get :children
        end
      end
      get "tasks/:id/comments" => "tasks#comments"
      post "tasks/:id/comments" => "tasks#post_comment"
    end
  end

  resources :cost_types
  resources :costs
  resources :wages
  resources :users, only: [] do
    collection do
      get :search_users
    end
  end
  resources :work_periods do
    collection do
      get :filter_by
      get :check_budget
      post :send_exceeded_log_hours_notification
    end
  end
  resources :high_schools, only: [:index]
  resources :removed_tasks, only: [:index]
  resources :addresses do
    collection do
      get :find_place
    end
  end
  resources :tasks do
    member do
      get :show_task
    end
    collection do
      get :task_vital_tasks
      get :task_pay_item
      get :filter_tasks
      get :search_tasks
      get :check_task_budget
    end

    member do
      get :remaining_budget
      get :task_summary
      get :task_snapshot
      put :check_task_date_range
      match :check_budget, via: [:get, :put]
      put :remove_task
      put :recover_task
    end
  end
  resources :task_users do
    collection do
      put :switch_role
    end
  end

  resources :pay_item_categories, only: [] do
    collection do
      get :search_pay_items
    end
  end

  namespace :reports do
    resource :staff_hours, only: [:show]
    resource :budget_reports, only: [:show]
  end

  get 'home/index'
  get 'home/user_list'
  get 'home/pay_items'

  # reporting
  get 'reports' => :index, controller: :reports
  get 'reports/staff_hours_view' => :index, controller: :reports
  get 'reports/budget_reports_view' => :index, controller: :reports

  # timesheet
  get 'timesheet/current_timesheet', as: :current_timesheet
  post 'timesheet/send_timesheet', as: :send_timesheet

  #xero authentication
  get 'xero_session/new' => 'xero_session#new', as: :xero_new_session

  devise_for :users,
             controllers: {
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords'
             }
  root 'home#index'
  get 'task/:id' => 'tasks#main', as: :task_id
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :cost_type
  belongs_to :user
  belongs_to :task
end

app/models/cost_type.rb
class CostType < ActiveRecord::Base
  has_many :costs
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:amount, :cost_type_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= simple_form_for(@cost, :html =>{ class: 'ui form'}) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input :amount %>
  </div>
  <div class="field">
    <%= f.label :cost_type %>
    <%= f.select :cost_type_id, options_for_select(CostType.all.map{ |ct| [ct.cost_type, ct.id]}) %>
  </div>
  <div class="field">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Costs</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.amount %></td>
        <td><%= cost.cost_type.cost_type %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>
<p>
  <strong>Type:</strong>
  <%= @cost.cost_type.cost_type %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>